[package]
name = "image-button"
version = "0.1.0"
edition = "2021"

[dependencies]
tracing = "0.1.44"
tracing-subscriber = "0.3.22"

[dependencies.libcosmic]
path = "../../"
features = ["debug", "winit", "wgpu", "tokio"]
